title: GoogleAds_Data_Dashboard
#logo: /assets/circular_headshot (2).png
#theme: jekyll-theme-minimal
#remote_theme: pages-themes/modernist@v0.2.0
#plugins:
- jekyll-remote-theme 
#remote_theme: "jekyll/minima@1e8a445"
remote_theme: pages-themes/slate@v0.2.0
